### ISSUE TITLE
Download artifacts

### ISSUE THREAD

**Issue by Zooip** [dsoftwareinc/ghactions-manager#121]
It would be pretty neat if we could open artifacts directly from the plugin.

My Cypress jobs generate logs and screenshots  and debugging would be much faster this way

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/121">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/121/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/121/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
download what artifacts?

**Comment by cunla** [comment]
https://api.github.com/repos/cunla/ghactions-manager/actions/artifacts
https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

**Comment by cunla** [comment]
Done in 2024.1.1
