### ISSUE TITLE
Add Support for Enterprise GitHub Server in IDE Plugin

### ISSUE THREAD

**Issue by diamond-cloud** [dsoftwareinc/ghactions-manager#147]
**Is your feature request related to a problem? Please describe.**
The current version of the IDE plugin does not support Enterprise GitHub servers. This limitation restricts users who are part of organizations that use Enterprise GitHub servers for their development work.

**Describe the solution you'd like**
The IDE plugin should be able to connect to both public GitHub and Enterprise GitHub servers. Plugin should be able to resolve actions

**Additional context**
This feature will be beneficial for developers working in organizations that use Enterprise GitHub servers.
Now the IDE can connect to the Enterprise GitHub Server, but the plugin cannot select this server
![telegram-cloud-photo-size-2-5307904551187241590-x](https://github.com/dsoftwareinc/ghactions-manager/assets/64248437/7b2da475-f56a-4a2d-9d6b-c6913b2b1ca4)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/147">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/147/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/147/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Actions are resolved by scanning the repositories in the workspace.

More elaborately: 
- It checks what repositories exist in the open project.
- Determine the actions server path according to the remote of these.
- If there is no repository mapping (e.g., you are working on a local project with no remote) - it will take github.com.

I figured if you are using actions, they should be in the same server of the remote of the project you are working on.

Can you describe your project? if you run `git remote -v`, what do you get? if you go to `Git Remotes` in the IDE, what do you get?

**Comment by diamond-cloud** [comment]
> Actions are resolved by scanning the repositories in the workspace.
> 
> More elaborately:
> 
> * It checks what repositories exist in the open project.
> * Determine the actions server path according to the remote of these.
> * If there is no repository mapping (e.g., you are working on a local project with no remote) - it will take github.com.
> 
> I figured if you are using actions, they should be in the same server of the remote of the project you are working on.
> 
> Can you describe your project? if you run `git remote -v`, what do you get? if you go to `Git Remotes` in the IDE, what do you get?

Yes, sure
![telegram-cloud-photo-size-2-5310156351000927420-y](https://github.com/dsoftwareinc/ghactions-manager/assets/64248437/32554ee2-469a-4100-8091-f4712c050ab0)
![telegram-cloud-photo-size-2-5310156351000927425-y](https://github.com/dsoftwareinc/ghactions-manager/assets/64248437/0eb154a0-6495-4157-b95b-6d0bd791f4d5)

**Comment by cunla** [comment]
ok, then it should try to resolve actions from the github enterprise server... I'll check

**Comment by diamond-cloud** [comment]
> ok, then it should try to resolve actions from the github enterprise server... I'll check

in my case it goes like this
<img width="775" alt="image" src="https://github.com/dsoftwareinc/ghactions-manager/assets/64248437/1c783932-2aab-494f-94dc-d0899bbd7602">

**Comment by cunla** [comment]
... This is not from ghactions-mgr pluging. When the action is not resolved in ghactions-mgr, it should be marked with red and show a different text:
![image](https://github.com/dsoftwareinc/ghactions-manager/assets/3419721/976565ca-191e-4437-8838-e5bf5ac079ae)

**Comment by diamond-cloud** [comment]
> ... This is not from ghactions-mgr pluging. When the action is not resolved in ghactions-mgr, it should be marked with red and show a different text: ![image](https://private-user-images.githubusercontent.com/3419721/327961308-976565ca-191e-4437-8838-e5bf5ac079ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDAxNDgsIm5iZiI6MTcxNDgzOTg0OCwicGF0aCI6Ii8zNDE5NzIxLzMyNzk2MTMwOC05NzY1NjVjYS0xOTFlLTQ0MzctODgzOC1lNWJmNWFjMDc5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMTYyNDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUwZGU5OTYzZGI5NjFhMjczMDY2MzUzZTNiMzRlNjVjZTUzNzkwM2U3ODA0YzE4NTA3NmE1Mjg1ZmVmOTc1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hAUdgR0shq0L914Pml3C2HjnNoO1JR63o9OdqEVaXMs)

Спасибо, прошу прощения

**Comment by cunla** [comment]
нет проблем, пожалуйста, скажите что-нибудь еще
