### ISSUE TITLE
The plugin com.dsoftware.ghtoolbar failed to save settings. Please restart PyCharm

### ISSUE THREAD

**Issue by ckarli** [dsoftwareinc/ghactions-manager#163]
### Describe the bug
![image](https://github.com/dsoftwareinc/ghactions-manager/assets/87313837/a6f20ad9-124a-4cad-9293-2d5d0fdb049e)

**Describe the bug:**
Everytime I save a file, a notification pops up.

### Steps to reproduce
Just save any file

### Expected behavior
No popups preferably

### Additional context

Plugin version: 2024.2.0
IDE: PyCharm 2024.1.2
OS: Windows 11

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/163">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/163/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/163/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for bringing this up. I'll submit a fix this week.
