### ISSUE TITLE
com.intellij.util.IncorrectOperationException: Sorry but parent: com.dsoftware.ghmanager.viewmodel.ViewModel@7cac7c89 (class com.dsoftware.ghmanager.viewmodel.ViewModel) has already been disposed (see the cause for stacktrace) so the child: com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=] (class com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanel) will never be disposed

### ISSUE THREAD

**Issue by maxviazov** [dsoftwareinc/ghactions-manager#177]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

com.intellij.util.IncorrectOperationException: Sorry but parent: com.dsoftware.ghmanager.viewmodel.ViewModel@7cac7c89 (class com.dsoftware.ghmanager.viewmodel.ViewModel) has already been disposed (see the cause for stacktrace) so the child: com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=] (class com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanel) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:156)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanel.<init>(LogConsolePanel.kt:25)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper.onCompleted$lambda$5(LogConsolePanelWrapper.kt:111)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:66)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$10

### Additional context

Plugin version: 2024.2.6
IDE: IntelliJ IDEA 2024.2 (IU-242.20224.300)
OS: macOS 15.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/177">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/177/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/177/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting. I fixed the tree for disposables in 2024.2.7
