### ISSUE TITLE
com.intellij.diagnostic.PluginException: class org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl cannot be cast to class org.jetbrains.yaml.psi.YAMLSequence (org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl and org.jetbrains.yaml.psi.YAMLSequence are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @8907271) [Plugin: com.dsoftware.ghtoolbar]

### ISSUE THREAD

**Issue by jjrawlins** [dsoftwareinc/ghactions-manager#185]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**
It threw this error at startup.  Behavior seems fine otherwise.  Might be a race condition.

#### Stack trace

com.intellij.diagnostic.PluginException: class org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl cannot be cast to class org.jetbrains.yaml.psi.YAMLSequence (org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl and org.jetbrains.yaml.psi.YAMLSequence are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @8907271) [Plugin: com.dsoftware.ghtoolbar]
	at com.dsoftware.ghmanager.psi.model.DispatchableWorkflowInput$Companion.fromYaml(DispatchableWorkflow.kt:36)
	at com.dsoftware.ghmanager.psi.ProjectStartup.registerDispatchableWorkflow(ProjectStartup.kt:83)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile$lambda$5(ProjectStartup.kt:58)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile(ProjectStartup.kt:49)
	at com.dsoftware.ghmanager.psi.ProjectStartup.execute$lambda$2(ProjectStartup.kt:38)
	at com.dsoftware.ghmanager.psi.ProjectStartup.execute(ProjectStartup.kt:34)

### Steps to reproduce

Start up WebStorm via terminal alias command - ws='open -a /Applications/WebStorm.app'

### Additional context

Plugin version: 2024.2.13
IDE: WebStorm 2024.2.3 (WS-242.23339.15)
OS: macOS 14.6.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/185">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/185/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/185/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting this. I will address it promptly.

**Comment by cunla** [comment]
This is an interesting error - I am not sure exactly how this can happen since there is an explicit check in the code before casting.

Were you editing the file when it happened?

Do you mind passing the yaml file text here?

**Comment by cunla** [comment]
I need more information in order to address this. I am closing this for now.
If you can provide the additional details, please add them here and reopen the issue
