### ISSUE TITLE
com.intellij.diagnostic.PluginException: Access is allowed from write thread only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction ; see https://jb.gg/ij-platform-threading for details

### ISSUE THREAD

**Issue by Ayfri** [dsoftwareinc/ghactions-manager#186]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

SystemEventQueueThread: (same) [Plugin: com.dsoftware.ghtoolbar]

### Additional context

Plugin version: 2024.2.13
IDE: WebStorm 2024.3 RC (WS-243.21565.120)
OS: Windows 11.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/186">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/186/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/186/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting this. I'll look into it.

**Comment by cunla** [comment]
Can you provide the stack trace?

**Comment by Ayfri** [comment]
Sorry I have no idea on how to get it, I just clicked on "report error" from the EAP :/

**Comment by cunla** [comment]
Does it happen when you are doing something in particular? opening a project? opening a workflow file?

**Comment by Ayfri** [comment]
When opening a project.

**Comment by cunla** [comment]
Does it happen in the new version (the non release candidate version)?

**Comment by Ayfri** [comment]
Nope, it's not happening anymore!
