### ISSUE TITLE
Issue still exists loading GHES Actions

### ISSUE THREAD

**Issue by ahenriksen-inferno** [dsoftwareinc/ghactions-manager#197]
### Describe the bug

@cunla - Apologies, but I still have the GHES Actions loading issue. Is the action definition not loading because I'm using a self-hosted GHES instance instead of one hosted by GitHub? In case it helps, here is what my project and environment looks like:

- The project source is hosted on a self-hosted GHES server behind a VPN.
- The project uses GH Actions from the public GitHub.com Marketplace and the GHES server.
- I have 3 GitHub accounts in my IDE (WebStorm):
    - Primary: GitHub.com Account 1
    - Secondary: GHES Account
    - Tertiary: GitHub.com Account 2

Please let me know if I need to do something differently with the plugin or if I can provide any additional information to help.

### Steps to reproduce

Here is what I've tried after installing the latest version of the plugin:

1. I left things as-is, opened a GH workflow, and saw that the GHES-hosted Action shows as unknown. I tried reloading the action definition and received this error:

    <img width="387" alt="SnagitHelper2024 2024-12-03 08 17 40" src="https://github.com/user-attachments/assets/f7885783-d02c-4eb0-ba33-f1477464030c">

2. I changed the default GitHub account from my public account to the GHES account and received the following error when trying to reload the action definition for the GHES Action:

    <img width="388" alt="SnagitHelper2024 2024-12-03 08 16 22" src="https://github.com/user-attachments/assets/e849194e-8098-4de2-9ab1-af722119ac52">

    Also, the definitions of the public GH Actions would not load.

### Additional context

Plugin version: `2024.3.1`
IDE: `WebStorm`
OS: `macOS`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/197">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/197/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/197/pledge.svg">
</picture>
</a>

**Comment by ahenriksen-inferno** [comment]
@cunla - Thank you. Is there any additional information I can provide that will help?

**Comment by cunla** [comment]
Do you know how to enable debug logs for a package? Here are instructions:
https://youtrack.jetbrains.com/articles/SUPPORT-A-43/How-to-enable-debug-logging-in-IntelliJ-IDEA


If so, the logs for `com.dsoftware.ghmanager` package would help..

**Comment by cunla** [comment]
Nevermind, I found the issue.
Next version should be fixed.

**Comment by ahenriksen-inferno** [comment]
@cunla - Ok, great! Apologies, it's been a busy day, and I'm just now seeing your message.

**Comment by cunla** [comment]
All good, thank you for reporting this! It is a unique edge case.
