### ISSUE TITLE
Open pull request in IntelliJ

### ISSUE THREAD

**Issue by bric3** [dsoftwareinc/ghactions-manager#86]
**Is your feature request related to a problem? Please describe.**
If using IntelliJ Ultimate (or any IDE that has the github Pull Request support), propose to open the PR in the IDE.

**Describe the solution you'd like**
The plugin already has a right click menu on the PR list, I believe one "just" needs to add an `AnAction` to the action groups of this menu. The action visibility can be check if the Github plugin is enabled (I believe this is bundled by default).

<img width="308" alt="image" src="https://user-images.githubusercontent.com/803621/227957741-e92dbc13-cca9-4c02-9f8b-3da9afe29879.png">

**Describe alternatives you've considered**
Go manually to the PR.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/86">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/86/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/86/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Well, as usual with the intellij github plugin, it is not as simple.
You can't simply link the existing action `GHPROpenPullRequestAction` because it needs all the data context in a specific format.

**Comment by cunla** [comment]
No... I did ask on their slack, but do you mind opening an issue on youtrack?

**Comment by bric3** [comment]
No I have no problem to open the issue, however I fear lack the technical context there.

Ideally one should be able to open a PR (in the toolwindow, maybe the timeline as well) in IJ, from the repository and the PR id.

**Comment by cunla** [comment]
v2024.2.0
